import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { ClientError } from "../errors.ts";
import { logger } from "../logging/logger.ts";
import type { ToolResultBlock } from "../types.ts";
import type { ContentBlock, LlmClient, LlmRequest, LlmResponse, ToolDefinition } from "./types.ts";

export interface PiConfig {
	model?: string;
	cwd?: string;
	piPath?: string;
	timeoutMs?: number;
}

// ─── Pi JSONL event types ──────────────────────────────────────────────────────

interface PiUsage {
	input_tokens?: number;
	output_tokens?: number;
}

interface PiToolUseBlock {
	type: "tool_use";
	id?: string;
	name: string;
	input: Record<string, unknown>;
}

interface PiTextBlock {
	type: "text";
	text: string;
}

type PiContentBlock = PiToolUseBlock | PiTextBlock | { type: string };

interface PiMessage {
	content: PiContentBlock[];
	stop_reason?: string;
	usage?: PiUsage;
	model?: string;
}

interface PiMessageEndEvent {
	type: "message_end";
	message: PiMessage;
}

type PiEvent = PiMessageEndEvent | { type: string };

// ─── Pure helper functions (exported for testability) ─────────────────────────

/**
 * Generate the content of a Pi extension file that registers Sapling's tool
 * schemas. Pi uses TypeBox's Type.Unsafe() for JSON Schema registration, and
 * registerTool() to declare each tool to the AI backend.
 *
 * The generated handler is a no-op stub — Sapling's agent loop handles actual
 * tool execution; the extension only exists so the model has proper tool schemas.
 */
export function generateExtensionContent(tools: ToolDefinition[]): string {
	const registrations = tools
		.map((t) => {
			const desc = t.description.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
			const schemaJson = JSON.stringify(t.input_schema);
			return `registerTool("${t.name}", "${desc}", Type.Unsafe(${schemaJson}), async (_input) => "");`;
		})
		.join("\n");

	return `// Auto-generated by Sapling PiClient — do not edit
import { registerTool, Type } from "pi";

${registrations}
`;
}

/**
 * Parse JSONL stdout from a Pi subprocess into an array of events.
 * Skips blank lines and malformed JSON.
 */
export function parseJsonlEvents(stdout: string): PiEvent[] {
	const events: PiEvent[] = [];
	for (const line of stdout.split("\n")) {
		const trimmed = line.trim();
		if (!trimmed) continue;
		try {
			const event = JSON.parse(trimmed) as PiEvent;
			events.push(event);
		} catch {
			// skip unparseable lines
		}
	}
	return events;
}

/**
 * Return the first message_end event from a parsed event list, or undefined.
 */
export function findResponse(events: PiEvent[]): PiMessageEndEvent | undefined {
	return events.find((e): e is PiMessageEndEvent => e.type === "message_end");
}

/**
 * Map a Pi content block to a Sapling ContentBlock.
 * Returns undefined for unknown block types.
 * Tool names are normalised to lowercase.
 */
export function mapContent(block: PiContentBlock): ContentBlock | undefined {
	if (block.type === "tool_use") {
		const tb = block as PiToolUseBlock;
		return {
			type: "tool_use",
			id: tb.id ?? crypto.randomUUID(),
			name: tb.name.toLowerCase(),
			input: tb.input ?? {},
		};
	}
	if (block.type === "text") {
		const txtb = block as PiTextBlock;
		return { type: "text", text: txtb.text };
	}
	return undefined;
}

/**
 * Map Pi's stop_reason string to Sapling's union stopReason.
 *   "toolUse"   → "tool_use"
 *   "maxTokens" → "max_tokens"
 *   anything else (including "stop") → "end_turn"
 */
export function mapStopReason(
	stopReason: string | undefined,
): "end_turn" | "tool_use" | "max_tokens" {
	switch (stopReason) {
		case "toolUse":
			return "tool_use";
		case "maxTokens":
			return "max_tokens";
		default:
			return "end_turn";
	}
}

// ─── Internal serialization helpers (mirrors cc.ts) ───────────────────────────

function serializeContentBlock(block: ContentBlock | ToolResultBlock): string {
	if (block.type === "text") {
		return block.text;
	}
	if (block.type === "tool_result") {
		return block.content;
	}
	return `[Tool Call: ${block.name}(${JSON.stringify(block.input)})]`;
}

function serializeMessageContent(content: string | (ContentBlock | ToolResultBlock)[]): string {
	if (typeof content === "string") {
		return content;
	}
	return content.map(serializeContentBlock).join("\n");
}

// ─── PiClient ─────────────────────────────────────────────────────────────────

export class PiClient implements LlmClient {
	readonly id = "pi";

	private readonly model: string | undefined;
	private readonly cwd: string;
	private readonly piPath: string;
	private readonly timeoutMs: number;

	constructor(config?: PiConfig) {
		this.model = config?.model;
		this.cwd = config?.cwd ?? process.cwd();
		this.piPath = config?.piPath ?? "pi";
		this.timeoutMs = config?.timeoutMs ?? 120_000;
	}

	estimateTokens(text: string): number {
		return Math.ceil(text.length / 4);
	}

	async call(request: LlmRequest): Promise<LlmResponse> {
		// Serialize conversation history to text, same approach as CcClient.
		const promptLines: string[] = [];
		for (const msg of request.messages) {
			const content = serializeMessageContent(
				msg.content as string | (ContentBlock | ToolResultBlock)[],
			);
			promptLines.push(`[${msg.role === "user" ? "User" : "Assistant"}]: ${content}`);
		}
		const conversation = promptLines.join("\n");

		// Write a temporary extension file when tools are present so the model
		// receives proper tool schemas via Pi's native tool calling API.
		let extDir: string | undefined;
		let extPath: string | undefined;
		if (request.tools.length > 0) {
			extDir = fs.mkdtempSync(path.join(os.tmpdir(), "sapling-pi-"));
			extPath = path.join(extDir, "ext.ts");
			fs.writeFileSync(extPath, generateExtensionContent(request.tools));
		}

		try {
			const args: string[] = [this.piPath, "-p", "--mode", "json", "--no-tools"];

			if (extPath) {
				args.push("-e", extPath);
			}

			args.push("--system-prompt", request.systemPrompt);

			if (request.model ?? this.model) {
				args.push("--model", (request.model ?? this.model) as string);
			}

			args.push(conversation);

			logger.debug("Spawning Pi subprocess", {
				pi: this.piPath,
				model: request.model ?? this.model,
				conversationLength: conversation.length,
			});

			// Wrap spawn in an IIFE so proc is const-typed (preserving Bun's pipe overload inference)
			// while still allowing us to catch PI_NOT_FOUND synchronously.
			const { proc, spawnErr } = (() => {
				try {
					return {
						proc: Bun.spawn(args, {
							cwd: this.cwd,
							stdin: "ignore",
							stdout: "pipe",
							stderr: "pipe",
						}),
						spawnErr: undefined,
					};
				} catch (err) {
					return { proc: undefined, spawnErr: err as NodeJS.ErrnoException };
				}
			})();
			if (!proc) {
				if (spawnErr?.code === "ENOENT") {
					throw new ClientError(`Pi CLI not found at '${this.piPath}'`, "PI_NOT_FOUND");
				}
				throw new ClientError(
					`Pi subprocess failed to start: ${spawnErr?.message ?? "unknown"}`,
					"PI_FAILED",
				);
			}

			// Drain stdout/stderr concurrently with a timeout to prevent deadlock
			// on large output or hung subprocesses.
			const drainPromise = Promise.all([
				proc.exited,
				new Response(proc.stdout).text(),
				new Response(proc.stderr).text(),
			]);
			let timeoutId: ReturnType<typeof setTimeout> | undefined;
			const timeoutPromise = new Promise<never>((_, reject) => {
				timeoutId = setTimeout(() => {
					reject(
						new ClientError(`Pi subprocess timed out after ${this.timeoutMs}ms`, "PI_TIMEOUT"),
					);
					proc.kill();
				}, this.timeoutMs);
			});
			const [exitCode, stdout, stderr] = await Promise.race([drainPromise, timeoutPromise]).finally(
				() => {
					clearTimeout(timeoutId);
				},
			);

			logger.debug("Pi subprocess exited", { exitCode, stdoutLength: stdout.length });

			if (exitCode !== 0) {
				throw new ClientError(`Pi subprocess failed: ${stderr}`, "PI_FAILED");
			}

			const events = parseJsonlEvents(stdout);
			const messageEnd = findResponse(events);

			if (!messageEnd) {
				throw new ClientError(
					`Pi subprocess produced no message_end event. Output: ${stdout.slice(0, 500)}`,
					"PI_NO_RESPONSE",
				);
			}

			const { message } = messageEnd;
			const content: ContentBlock[] = [];

			for (const block of message.content ?? []) {
				const mapped = mapContent(block);
				if (mapped) {
					content.push(mapped);
				}
			}

			if (content.length === 0) {
				throw new ClientError(
					`Pi message_end contained no usable content blocks. Output: ${stdout.slice(0, 500)}`,
					"PI_INVALID_OUTPUT",
				);
			}

			const stopReason = mapStopReason(message.stop_reason);
			const usage = message.usage ?? {};

			return {
				content,
				usage: {
					inputTokens: usage.input_tokens ?? 0,
					outputTokens: usage.output_tokens ?? 0,
				},
				model: message.model ?? request.model ?? this.model ?? "unknown",
				stopReason,
			};
		} finally {
			// Best-effort cleanup of temporary extension directory.
			if (extDir) {
				try {
					fs.rmSync(extDir, { recursive: true, force: true });
				} catch {
					// ignore
				}
			}
		}
	}
}
